version: "3.9"

services:
  nginx:
    container_name: nginx
    build: nginx
    domainname: localhost
    hostname: localhost
    ports:
      - "443:443"
    networks:
      - project

  wordpress:
    container_name: wordpress
    build: wordpress
    networks:
      - project
    ports:
        - "9000:9000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

networks:
  project:
    driver: bridge